name: islamly
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

 # For images used
  flutter_svg: ^2.0.5


# for state management
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1


# For for validation
  formz: ^0.6.0


# For condole messagews
  logger: ^1.3.0

# for routes navigations
  go_router: ^7.0.0


# fonts for the app 
  google_fonts: ^4.0.4


  # sizes
  flutter_screenutil: ^5.7.0


  # locla storage
  flutter_secure_storage: ^8.0.0  

 # Launcher app screen
  flutter_native_splash: ^2.2.19


 # SOCIALS APP LOGIN
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^4.3.0 
  flutter_facebook_auth: ^5.0.11

  # FIREBASE PACKAGES
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter


  # For models from json data  
  freezed: ^2.3.3
  build_runner: ^2.3.3
  json_serializable: ^6.6.2

  # for translation
  fast_i18n: ^5.12.6

  # for app icon geeration
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0





# Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.jpeg"

  

flutter:


  uses-material-design: true



  assets:
    - assets/images/
    - assets/icons/


#flutter pub run flutter_native_splash:create
flutter_native_splash:


  image: assets/images/splash.png

  color: "#F9FAFB"
  fullscreen: true