name: ubiza
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_secure_storage: ^6.0.0
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  formz: ^0.4.1
  font_awesome_flutter_named: ^1.1.1+2
  fluttertoast: ^8.1.1
  http: ^0.13.5
  json_annotation: ^4.6.0
  cached_network_image: ^3.2.3
  fade_shimmer: ^2.2.0

  # FIREBASE PACKAGES
  firebase_auth: ^4.1.3
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.2.0
  cloud_firestore: ^4.1.0
  flutter_facebook_auth: ^5.0.6
  firebase_storage: ^11.0.6
  # Additional Firebase packages. To prevent unexpected upgrade.
  firebase_auth_platform_interface: ^6.11.3
  cloud_firestore_platform_interface: ^5.9.0
  firebase_storage_platform_interface: ^4.1.24

  # PERMISSION
  permission_handler: ^10.2.0

  logger: ^1.1.0
  intl: ^0.17.0

  #FONTS
  google_fonts: ^3.0.1

  #GALLARY
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_launcher_icons: ^0.10.0  


  flutter_lints: ^2.0.0

# Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
       